version: 3.7

services:
  ruuvi-shell:
    build: .
    container_name: ruuvi-shell
    restart: always
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - TZ=Europe/Helsinki
    networks:
      - mysql
  ruuvi-api:
    build: ../ruuvi-api
    container_name: ruuvi-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: ruuvi
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ruuvi
      SERVER_PORT: 8080
    networks:
      - mysql
  mysql:
      image: mysql-9.2
      restart: always
      expose:
        - 3306
      ports:
        - "127.0.0.1:3306:3306" # For connections from host
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      networks:
        - mysql
networks:
  mysql: